[package]
name = "nes_palette"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
rgb24 = "0.3"

[dev-dependencies]
ansi_term = "0.12"

[[example]]
name = "print_rgb"
