[package]
name = "glutin_frontend"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
glutin = "0.20"
gfx_window_glutin = "0.30"
gfx_device_gl = "0.16"
gfx = "0.18"

[[example]]
name = "test_pattern"
