[package]
name = "samples"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
mos6502_assembler = { path = "../assembler" }
mos6502_model = { path = "../model" }
