[package]
name = "samples"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
assembler = { path = "../assembler" }
mos6502 = { path = "../mos6502" }
