[package]
name = "butterfly"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
mos6502_assembler = { path = "../assembler" }
mos6502_model = { path = "../model" }
ines = { path = "../ines" }
