[package]
name = "nes_name_table_debug"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
nes_specs = { path = "../nes-specs" }
nes_palette = { path = "../nes-palette" }
