[package]
name = "conway"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
assembler = { path = "../assembler" }
mos6502 = { path = "../mos6502" }
ines = { path = "../ines" }
